// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function GetCurrencies(arg1:string):Promise<main.response>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFileDialog():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
