// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function GetCurrencies(arg1) {
  return window['go']['main']['App']['GetCurrencies'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFileDialog() {
  return window['go']['main']['App']['SaveFileDialog']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
