// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDocument(arg1, arg2) {
  return window['go']['main']['App']['ChooseDocument'](arg1, arg2);
}

export function ChooseOrCreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChooseOrCreateFolder'](arg1, arg2, arg3);
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function DirOfFile(arg1) {
  return window['go']['main']['App']['DirOfFile'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function Print() {
  return window['go']['main']['App']['Print']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RelativePath(arg1, arg2) {
  return window['go']['main']['App']['RelativePath'](arg1, arg2);
}

export function ResetQuit() {
  return window['go']['main']['App']['ResetQuit']();
}

export function SanitizeName(arg1) {
  return window['go']['main']['App']['SanitizeName'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveCsvDialog(arg1) {
  return window['go']['main']['App']['SaveCsvDialog'](arg1);
}

export function SaveFileDialog() {
  return window['go']['main']['App']['SaveFileDialog']();
}

export function SelectDocumentDialog() {
  return window['go']['main']['App']['SelectDocumentDialog']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
