// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function CreateDirectory(arg1:string):Promise<void>;

export function DirOfFile(arg1:string):Promise<string>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetVersion():Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function Print():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function RelativePath(arg1:string,arg2:string):Promise<string>;

export function ResetQuit():Promise<void>;

export function SaveCsvDialog(arg1:string):Promise<string>;

export function SaveFileDialog():Promise<string>;

export function SelectDocumentDialog():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
